name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install packages and run tests
        run: |
          node -v
          npm install
          npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Prepare Build
        run: |
          node -v
          npm install
          npm run build
      - name: Deploy Build
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          publish_dir: ./build
